doc fixes

diff --git a/update_docs b/update_docs
--- a/update_docs
+++ b/update_docs
@@ -3,7 +3,9 @@
 cd doc
 printf "\n\nUpdating API documentation and testing html compilation\n\n"
 sleep 1
-make clean ; make html
+make clean
+failed=0
+make html || failed=1
 git add api
 git add pypeit_par.rst
 cd ../
@@ -13,7 +15,11 @@ GREEN='\033[0;32m'
 NC='\033[0m' # No Color
 
 nwarnings=$(wc -l "doc/sphinx_warnings.out" | awk '{print $1}')
-if [ ${nwarnings} -ne 0 ]; then
+if [ ${failed} -ne 0 ]; then
+    printf "\n\n${RED}============================${NC}\n"
+    printf "${RED}Sphinx build scripts FAILED!${NC}\n"
+    printf "${RED}============================${NC}\n\n"
+elif [ ${nwarnings} -ne 0 ]; then
     printf "\n\n${RED}====================${NC}\n"
     printf "${RED}Sphinx build FAILED: ${nwarnings} warnings found.${NC}\n"
     printf "${RED}====================${NC}\n\n"
